# Generated by Django 4.2.1 on 2023-08-02 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_postmodel_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='create_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
